name: typesafe_firebase
description: "A flutter library providing a type safe wrapper on firebase."
version: 0.0.2
repository: https://github.com/vikram-agrawal/typesafe_firebase

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_functions: ^6.0.5
  firebase_core: ^4.3.0
  meta: ^1.17.0
  json_annotation: ^4.9.0
  analyzer: ^9.0.0
  build: ^4.0.3
  json_serializable: ^6.11.3
  source_gen: ^4.1.1
  glob: ^2.1.3
  path: ^1.9.1
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  mocktail: ^1.0.4
  mockito: ^5.6.3
  firebase_auth_platform_interface: ^8.1.5
  cloud_functions_platform_interface: ^5.8.8

flutter:
