name: typesafe_firebase_firestore
description: "A flutter library providing a type safe wrapper on firebase."
version: 0.0.2
repository: https://github.com/vikram-agrawal/typesafe_firebase/tree/main/typesafe_firebase_firestore

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.1.1
  meta: ^1.17.0
  typesafe_firebase_core: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
