name: typesafe_firebase_generator
description: "A flutter library providing a type safe wrapper on firebase."
version: 0.0.3
repository: https://github.com/vikram-agrawal/typesafe_firebase

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.4
  source_gen: ^4.1.2
  typesafe_firebase: ^0.0.3
  analyzer: '>=6.0.0 <9.0.0'
  json_serializable: ^6.11.2
  glob: ^2.1.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
