name: typesafe_firebase_generator
description: "A flutter library providing a type safe wrapper on firebase."
version: 0.0.2
repository: https://github.com/vikram-agrawal/typesafe_firebase/tree/main/typesafe_firebase_generator

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^8.4.1
  build: ^4.0.4
  glob: ^2.1.3
  json_serializable: ^6.11.2
  path: ^1.9.1
  source_gen: ^4.1.2
  typesafe_firebase_core: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
