name: typesafe_firebase
description: "A flutter library providing a type safe wrapper on firebase."
version: 0.0.3
repository: https://github.com/vikram-agrawal/typesafe_firebase

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_functions: ^6.0.5
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
